# Generated by Django 3.2.3 on 2021-06-28 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='documents/')),
                ('types', models.CharField(blank=True, choices=[('audio', 'AUDIO'), ('images', 'IMAGES')], default=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='documents/')),
                ('types', models.CharField(blank=True, choices=[('audio', 'AUDIO'), ('images', 'IMAGES')], default=False, max_length=20)),
                ('messages', models.TextField(blank=True, max_length=100)),
                ('uniqueIds', models.UUIDField(blank=True, default=uuid.uuid1, editable=False)),
            ],
        ),
    ]
