# Generated by Django 3.2.3 on 2022-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnography', '0002_auto_20220129_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='types',
            field=models.CharField(choices=[('midi', 'MIDI'), ('wave', 'WAVE')], max_length=20),
        ),
    ]
