# Generated by Django 3.2.3 on 2022-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnography', '0004_alter_uploads_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='types',
            field=models.CharField(blank=True, choices=[('midi', 'MIDI'), ('wave', 'WAVE')], default='wave', max_length=20),
        ),
    ]
